### ISSUE TITLE
  How to export the scene generated by "prolificdreamer-scene.yaml" to a 3D mesh format?

### ISSUE THREAD

**Issue by caojiehui** [threestudio-project/threestudio#332] opened 2023-10-29 06:27 UTC
We use the following command to convert the scene into a 3D mesh format:

```
config_path=/home/yingjie/threestudio/outputs/prolificdreamer/Golden_rainwater_in_a_fantastical_weather,_realistic_detailed_photo,_4k@20231023-110627/configs/parsed.yaml
resume_path=/home/yingjie/threestudio/outputs/prolificdreamer/Golden_rainwater_in_a_fantastical_weather,_realistic_detailed_photo,_4k@20231023-110627/ckpts/last.ckpt
```

CUDA_VISIBLE_DEVICES=9 python launch.py --config $config_path --export resume=$resume_path system.exporter_type=mesh-exporter system.exporter.context_type=cuda system.geometry.isosurface_threshold=10.

The generated MP4 video results are excellent, but when using the above command to convert them into 3D mesh, the results are as shown in the following image:

![图片](https://github.com/threestudio-project/threestudio/assets/14066267/b27d8976-3dcc-4c08-8635-df8e8954b658)

Is there an issue with the command for converting to 3D mesh mentioned above? How should we modify it to generate 3D mesh data corresponding to the video in MP4 format?

**Comment by BA826974** [comment] 2023-11-11 09:09
github提问的咋全是中国人lol

**Comment by DSaurus** [comment] 2023-11-27 23:09
This issue is a duplicate of [#329], so I'm closing it to keep discussions centralized.

**Closed by DSaurus** 2023-11-27 23:09 UTC
