### ISSUE TITLE
magic3d visual gap between the end of coarse and the beginning of refine

### ISSUE THREAD

**Issue by chenglong0313** [threestudio-project/threestudio#45] opened 2023-05-11 08:13 UTC
Thank you a lot for your nice share!
I try to train magic3d with prompt "ironman, full body".
4 V100 cards and batchsize = 2 for each card

After the coarse stage  of magic3d training，the  visual images are as follows

https://github.com/threestudio-project/threestudio/assets/30063446/1cf21bd6-d60f-4a20-83a4-3f7208c226f2

But the initial visualization of refine stage is very different from the end of coarse stage,  after loading the weights. 
the initial visualization of refine stage are as follows
![it0-3](https://github.com/threestudio-project/threestudio/assets/30063446/82db6203-78b2-49ed-81ab-526f84c09d33)
![it0-0](https://github.com/threestudio-project/threestudio/assets/30063446/9e43025e-1ff5-42f5-ba85-21aa0b6e8353)
![it0-1](https://github.com/threestudio-project/threestudio/assets/30063446/2eb36fc3-cbff-4735-8987-f548f2f06e29)

This gap seems a bit big, is this result normal?
The final result of refine stage is as follows

https://github.com/threestudio-project/threestudio/assets/30063446/f588139c-9547-475f-a058-d7ace5eb5499

**Comment by bennyguo** [comment] 2023-05-11 08:34
Hi, the reasons are as follows:

- The extracted geometry is not accurate enough, due to inappropriate choice of isosurface threshold. By default, the threshold is automatically determined but often fails (leading to floaters and bbox that's not tight enough). You may manually specify a threshold value by `system.geometry.isosurface_threshold=some_float_value`, based on the automatically determined value shown in the console:
![image](https://github.com/threestudio-project/threestudio/assets/19284678/2b119efa-51d6-4927-9f63-79bd8d5ca272)

In your case, you should probably use a larger threshold value.

- Magic3D coarse stage uses predicted normals, which are not true geometric normals. However, the refinement stage uses true geometric normals of the mesh, which brings an appearance gap. This is the expected behavior. If you want to keep appearance consistency across stages, I recommend you using analytic normals in the coarse stage by setting `system.geometry.normal_type=analytic`.

Let me know if things get better.

**Comment by claforte** [comment] 2023-06-03 16:21
@bennyguo answered and @chenglong0313 hasn't replied in 3 weeks... I recommend we close this issue.

**Closed by claforte** 2023-06-03 16:21 UTC
